const express = require('express');
const { z } = require('zod');
const validate = require('../middlewares/validate.middleware');
const schemas = require('../validators/collaboration.validator');
const controller = require('../controllers/adminCollaboration.controller');
const router = express.Router();
const idParam = z.object({ id: schemas.id });
const memberParam = z.object({ id: schemas.id, userId: schemas.id });
const page = z.object({ page: z.coerce.number().int().min(1).max(1000).default(1) });
router.get('/friends', validate(page, 'query'), controller.listFriends);
router.delete('/friends/:id', validate(idParam, 'params'), controller.removeFriend);
router.get('/groups', validate(page, 'query'), controller.listGroups);
router.patch('/groups/:id', validate(idParam, 'params'), validate(schemas.groupUpdate), controller.updateGroup);
router.delete('/groups/:id', validate(idParam, 'params'), controller.removeGroup);
router.patch('/groups/:id/members/:userId', validate(memberParam, 'params'), validate(schemas.memberRole), controller.member);
router.delete('/groups/:id/members/:userId', validate(memberParam, 'params'), controller.member);
router.get('/shares', validate(page, 'query'), controller.listShares);
router.delete('/shares/:id', validate(idParam, 'params'), controller.removeShare);
module.exports = router;
