const express = require('express');
const { z } = require('zod');
const validate = require('../middlewares/validate.middleware');
const schemas = require('../validators/collaboration.validator');
const controller = require('../controllers/group.controller');
const router = express.Router();
const idParam = z.object({ id: schemas.id });
const memberParam = z.object({ id: schemas.id, userId: schemas.id });
router.get('/', controller.mine);
router.get('/search', validate(schemas.search, 'query'), controller.search);
router.get('/invitations', controller.invitations);
router.patch('/invitations/:id', validate(idParam, 'params'), validate(schemas.invitationDecision), controller.decide);
router.post('/', validate(schemas.groupCreate), controller.create);
router.get('/:id', validate(idParam, 'params'), controller.one);
router.patch('/:id', validate(idParam, 'params'), validate(schemas.groupUpdate), controller.update);
router.delete('/:id', validate(idParam, 'params'), controller.remove);
router.post('/:id/invitations', validate(idParam, 'params'), validate(schemas.groupInvite), controller.invite);
router.patch('/:id/owner', validate(idParam, 'params'), validate(schemas.groupInvite), controller.transferOwner);
router.patch('/:id/members/:userId', validate(memberParam, 'params'), validate(schemas.memberRole), controller.memberAction);
router.delete('/:id/members/:userId', validate(memberParam, 'params'), controller.memberAction);
module.exports = router;
